package creative

import (
	"bytes"
	_ "embed"
	"fmt"
	"log"
	"os"
)

var (
	AgentPromptFilename = "agent.out"
)

// ConflictPrompt contains the prompt template for conflict solving
//
//go:embed conflict.md
var ConflictPrompt Prompt

// Prompt represents a text prompt for AI agents
type Prompt string

// Agent represents an AI agent with name, role, and colleagues
// Valid ranges:
//   - Name: non-empty string, unique identifier
//   - Role: prompt describing agent's role and behavior
//   - Other: list of colleague agents (unexported, used internally)
type Agent struct {
	Name  string  // Short name of agent, must be non-empty
	Role  Prompt  // Role description prompt, must be non-empty
	other []Agent // Colleague agents (internal use)
}

// Run executes the agent with given input, output context, and mail threads
// input: task description string, can be empty but not recommended
// output: current consensus or agreements string, can be empty
// mails: mail threads relevant to this agent, can be empty
// Returns: slice of Mail objects generated by the agent
func (a Agent) Run(input, output string, mails string, contextSize int) []Mail {
	// Validate agent name
	if a.Name == "" {
		log.Printf("Warning: running agent with empty name")
	}

	log.Printf("Run agent: %s", a.Name)
	var buf bytes.Buffer

	// Build agent context prompt
	fmt.Fprintf(&buf, "Описание твоей имени\n")
	fmt.Fprintf(&buf, "%s\n", string(a.Name))
	fmt.Fprintf(&buf, "Окончание описания твоей имени\n")
	fmt.Fprintf(&buf, "\n")

	fmt.Fprintf(&buf, "Описание твоей роли\n")
	fmt.Fprintf(&buf, "%s\n", string(a.Role))
	fmt.Fprintf(&buf, "Окончание описания твоей роли\n")
	fmt.Fprintf(&buf, "\n")

	// Add colleague descriptions
	for _, c := range a.other {
		if c.Name == a.Name {
			continue // Skip self-reference
		}
		fmt.Fprintf(&buf, "Описание роли твоего коллеги по имени: `%s`\n", c.Name)
		fmt.Fprintf(&buf, "%s\n", string(c.Role))
		fmt.Fprintf(&buf, "Окончание описания роли `%s`\n", c.Name)
		fmt.Fprintf(&buf, "\n")
	}

	// Add task context
	fmt.Fprintf(&buf, "Общая задача, которую решается с точки зрения твоей роли\n")
	fmt.Fprintf(&buf, "%s\n", input)
	fmt.Fprintf(&buf, "Окончание описания общей задачи\n")
	fmt.Fprintf(&buf, "\n")

	// Add existing agreements if any
	fmt.Fprintf(&buf, "Достигнутые договоренности, принятые решения, резульата работы\n")
	if output != "" {
		fmt.Fprintf(&buf, "%s\n", output)
	} else {
		fmt.Fprintf(&buf, "Нет принятых договоренностей помеченных solved\n")
	}
	fmt.Fprintf(&buf, "Окончание описания достигнутых договоренности\n")
	fmt.Fprintf(&buf, "\n")

	// Add mailbox prompt for email generation
	fmt.Fprintf(&buf, "Правила работы с почтой\n")
	fmt.Fprintf(&buf, "%s\n", MailBoxPrompt)
	fmt.Fprintf(&buf, "Окончание правил работы с почтой\n")
	fmt.Fprintf(&buf, "\n")

	// Add conflict prompt for solving
	fmt.Fprintf(&buf, "Правила работы при конфликтах\n")
	fmt.Fprintf(&buf, "%s\n", ConflictPrompt)
	fmt.Fprintf(&buf, "Окончание правил работы при конфликтах\n")
	fmt.Fprintf(&buf, "\n")

	// Add mail threads if any
	if 0 < len(mails) {
		fmt.Fprintf(&buf, "Твой почтовый ящик\n")
		fmt.Fprintf(&buf, "%s\n", mails)
		fmt.Fprintf(&buf, "Окончание твоего почтового ящика\n")
		fmt.Fprintf(&buf, "\n")
	}

	if tokens := float64(len(buf.String())) / 2.; 0.7*float64(contextSize) < tokens {
		fmt.Fprintf(&buf, "ВАЖНО: Почта переполнена. Срочно подвести необходимо прийти к согласию, чтобы перевести письма в состояние solved. Заархивируй неиспользуемые заметки самому себе\n")
		fmt.Fprintf(&buf, "\n")
	}

	// Execute agent via AI
	if AI == nil {
		panic(fmt.Errorf("AI runner not initialized"))
	}

	request := buf.String()
	log.Printf("agent `%s` request length: %d", a.Name, len(request))

	if AgentPromptFilename != "" {
		// ignore error
		_ = os.WriteFile(AgentPromptFilename, []byte(request), 0777)
	}

	response, err := AI.Run(request)
	log.Printf("agent `%s` response: %s. Error = %v", a.Name, response, err)

	if err != nil {
		log.Printf("Error running agent %s: %v", a.Name, err)
		// Continue processing even with error as response may contain partial data
	}

	// Set sender for all generated mails
	for i := range response {
		response[i].From = a.Name
	}

	return response
}
